// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptosynohnnqsirwnyvxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0b3N5bm9obm5xc2lyd255dnh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzMwNzYsImV4cCI6MjA2Mzg0OTA3Nn0.3sA-j_YXOPCuLahCOc-X9ybeHU4GSijmclGdxsMEJ6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);